# Copyright (c) 2026, Lidar Holding Group S. A. and contributors
# For license information, please see license.txt

# import frappe
from frappe.model.document import Document


class HikvisionEvent(Document):
	# begin: Auto-generated methods
	# This code is auto-generated by Frappe
	# Do not modify this code

	def autoname(self):
		# Generate a unique name based on timestamp and random suffix
		import time
		import random
		self.name = f"HE-{int(time.time())}-{random.randint(1000, 9999)}"

	# end: Auto-generated methods

	pass
